package com.mks.dynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.mks.dynamodb.converter.TeacherCnovrter;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "school")
public class School {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String schoolName;
    @DynamoDBAttribute
    private String schoolAddress;
    @DynamoDBAttribute
    private List<Student> studentList;

    @DynamoDBTypeConverted(converter = TeacherCnovrter.class)
    @DynamoDBAttribute
    private Teacher teacher;
    @DynamoDBAttribute
    private List<Subject> subjectList;
}
